config/routes.rb
Rails.application.routes.draw do
  resources :members
  resources :matches do
  	collection do
  	  get :top_players
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/destroy_record.rb
module DestroyRecord
  extend ActiveSupport::Concern

  included do
    default_scope -> { where(is_deleted: false) }
  end

  def destroy     
    update_attribute(:is_deleted, true)
    run_callbacks :destroy
    freeze
  end 
end

app/models/match.rb
class Match < ApplicationRecord
  include DestroyRecord
  after_save :update_member_score

  JSON_LIST = [ :id, :player1, :player2, :score_player1, :score_player2, :created_at, :location]

  #Validation
  validates :player1, :player2, presence: true

  #Methods
  def self.get_match(match_id)
    match_info =  Match.find_by(id: match_id)
  end

  def update_member_score
  	#update won and loss count 
  	if score_player1 > score_player2
  	  Member.update_won_count(player1, score_player1, player2, score_player2)
  	else
      Member.update_won_count(player2, score_player2, player1, score_player1)
  	end

  	#Update avg and highest score of player1
  	Member.update_avg_score(player1)
  	Member.update_highest_score(player1, score_player1, id)

  	#Update avg and highest score of player2
  	Member.update_avg_score(player2)
  	Member.update_highest_score(player2, score_player2, id)
  end

  def as_json(option={})
    json = super(option)
    if player1 == option[:current_player_id]
      against_whom_id     = player2
    else
      against_whom_id     = player1
    end

    json[:against_whom] = Member.get_member(against_whom_id).name
    json
  end

end

app/models/member.rb
class Member < ApplicationRecord
  include DestroyRecord

  #scope
  scope :random, -> { order('RAND()') }

  #Validation
  validates :name, presence: true
  validates :contact_number, presence: true, uniqueness: { scope: :is_deleted }
  validates_length_of :name, minimum: 3, maximum: 50
  validates_length_of :contact_number, minimum: 11, maximum: 30

  #Methods
  def self.get_member member_id
    member = Member.find_by(id: member_id)
  end

  def self.update_won_count winner, winner_score, loser, loser_score
    winner_member = Member.get_member(winner)
    winner_member.update_attributes(
      won_matches: winner_member.won_matches+1, 
      total_score: winner_member.total_score+winner_score
      ) if winner_member.present?

    loser_member = Member.get_member(loser)
    loser_member.update_attributes(
      lost_matches: loser_member.lost_matches+1, 
      total_score: loser_member.total_score+loser_score 
      ) if loser_member.present?
  end

  def self.update_avg_score member_id
    member = Member.get_member(member_id)
    avg_score = member.total_score/(member.lost_matches+member.won_matches)
    member.update_attributes(avg_score: avg_score)
  end

  def self.update_highest_score member_id, highest_score, match_id
    member = Member.get_member(member_id)

    #member highest score is less then recent match score then update highest score
    if member.highest_score < highest_score
      member.update_attributes(highest_score: highest_score, highest_scored_match_id: match_id)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def top_players
  	@members = Member.group(:id).having("sum(won_matches+lost_matches) > 1").order(" avg_score DESC ").limit(10)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :contact_number, :is_deleted)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def self.readable_date date
    date.strftime("%d-%m-%y %I:%M %p")
  end
end

app/helpers/members_helper.rb
module MembersHelper
  def self.get_match_details match_id, current_player_id
    match_info = Match.get_match(match_id)
    match_info.as_json(only: Match::JSON_LIST, current_player: current_player_id)
  end

  def self.total_match_count(won,lost)
  	won+lost
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrabbleClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matches/top_players.html.erb
<p id="notice"><%= notice %></p>

<h1>Top Players List</h1>

<table>
  <thead>
    <tr>
      <th>Player Name</th>
      <th>Player Average Score</th>
      <th>Total Matches Played</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.avg_score %></td>
        <td><%= MembersHelper.total_match_count(member.won_matches, member.lost_matches) %></td>
        <td><%= link_to 'View Profile', member %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :contact_number %>
    <%= form.text_field :contact_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact number</th>
      <th>Created On</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.name %></td>
        <td><%= member.contact_number %></td>
        <td><%= ApplicationHelper.readable_date(member.created_at) %></td>
        <td><%= link_to 'View Profile', member %> | 
            <%= link_to 'Edit', edit_member_path(member) %>        
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @member.contact_number %>
</p>

<p>
  <strong>Number Of Wins:</strong>
  <%= @member.won_matches %>
</p>

<p>
  <strong>Number of losses:</strong>
  <%= @member.lost_matches %>
</p>

<p>
  <strong>Average Score:</strong>
  <%= @member.avg_score %>
</p>

<p>
  <strong>Highest Scored Match Details</strong> <br>
  <% match_details = @member.highest_scored_match_id.present? ? MembersHelper.get_match_details(@member.highest_scored_match_id, @member.id) : {} %>
  <% if match_details.present? %>
  	Highest Score : <%= @member.highest_score || 0 %> <br>
  	Scored On Date: <%= ApplicationHelper.readable_date(match_details["created_at"]) || "" %> <br>
  	Match Location: <%= match_details["location"] || "" %> <br>
  	Scored Against: <%= match_details[:against_whom] || "" %>
  <% end %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>